### ISSUE TITLE
build-essential dependency for DKMS install

### ISSUE THREAD

**Issue by Cypher1** [patjak/facetimehd#140]
I think the doc is missing 'build-essential' as a requirement for DKMS install.

Easy fix, I think. Just need something like
`
sudo apt install build-essential
`
In there, but I wanted to get feedback before making a PR (I don't have much experience with DKMS).

Thanks

**Comment by WhyNotHugo** [comment]
This should actually be a requirement of the package itself, not something DKMS installs itself.
